### ISSUE TITLE
Work with Docker

### ISSUE THREAD

**Issue by mikestecker** [beele/homebridge-unifi-protect-camera-motion#1]
Does this work with a Docker install of HomeBridge (using `oznu/homebridge`)? I'm getting the following error and I'm not sure if it's because of the docker install or not:

```
> @tensorflow/tfjs-node@1.2.11 install /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-1.2.11.tar.gz
* Downloading libtensorflow
[==============================] 32460038/bps 100% 0.0s
* Building TensorFlow Node.js bindings

> canvas@2.6.0 install /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v64-linux-musl-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.0 and node@10.16.3 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'pixman-1', required by 'virtual:world', not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-65-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-65-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN docker-homebridge@1.0.0 No description
npm WARN docker-homebridge@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-18T20_47_48_258Z-debug.log

Command failed. Please review log for details.
```

**Comment by beele** [comment]
I found your issue on the other github issue tracker (https://github.com/oznu/docker-homebridge/issues/239) I'll change it so typescript is in the regular dependencies

**Comment by beele** [comment]
The newer 0.0.3 version on npm has the typescript dependency no longer under dev dependencies but under the regular ones.

**Comment by mikestecker** [comment]
Everything seems to be working now. Thanks!
