### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot load image!

### ISSUE THREAD

**Issue by nzbullet** [beele/homebridge-unifi-protect-camera-motion#22]
Receiving the following error in my logs anytime motion is detected if enable anonymous snapshots is not enable. This Error should be handled more gracefully to advise the user what the issue is. 

```[3/28/2020, 22:36:13] [Unifi Protect] !!!! Unifi Motion event (5e7f1a6a00db7c03e70005d6) accepted for camera: Living Room Camera - Score: 76 !!!!
(node:3606) UnhandledPromiseRejectionWarning: Error: Cannot load image!
    at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/src/coco/loader.js:42:23)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/src/coco/loader.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:3606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)```

**Comment by beele** [comment]
Will look into this
