### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by alezanott** [beele/homebridge-unifi-protect-camera-motion#27]
Hi @beele, I've just made the update that you released today but got this error.
`at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)`

**Comment by beele** [comment]
If you update to the latest version it should be fixed.
TFJS-NODE seems to be very broken atm for running on a pi so I reverted it back and opened a bug ticket with them: https://github.com/tensorflow/tfjs/issues/3052

**Comment by alezanott** [comment]
Fixed it @beele! thank you
let's hope they'll answer to the ticket.

**Comment by beele** [comment]
No problem!
Hopefully it gets fixed so I can include an updated tfjs-node

**Comment by alezanott** [comment]
@beele after updating to the latest version I've encountered a similar issue as last time:
```
Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node. 
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module. 
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-unifi-protect-camera-motion/src/coco/coco.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```
Do I need to update something specific, since I'm in HOOBS environment is not so simple to get things running in sudo. Thank you
