### ISSUE TITLE
Unable to install on Synology+Docker

### ISSUE THREAD

**Issue by tillkruss** [beele/homebridge-unifi-protect-camera-motion#29]
Any leads on how to resolve this?

```
/homebridge # sudo npm install homebridge-unifi-protect-camera-motion -g --unsafe-perm=true
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/homebridge-unifi-protect-camera-motion failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> ffmpeg-for-homebridge@0.0.3 install /usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/ffmpeg-for-homebridge
> node install.js

ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.0 (Alpine 9.2.0)
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

ffmpeg has been downloaded to /usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/ffmpeg-for-homebridge/ffmpeg
Thank you for using https://github.com/homebridge/ffmpeg-for-homebridge


> @tensorflow/tfjs-node@1.2.11 install /usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-1.2.11.tar.gz
* Downloading libtensorflow
[==============================] 8116154/bps 100% 0.0s
* Building TensorFlow Node.js bindings

> canvas@2.6.1 install /usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-musl-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.1 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'pixman-1', required by 'virtual:world', not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.59+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.4.59+
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-28T02_43_06_049Z-debug.log
```

**Comment by beele** [comment]
You need to install the canvas dependencies. Look in the wiki: https://github.com/beele/homebridge-unifi-protect-camera-motion/wiki/node-canvas-prerequisites

**Comment by tillkruss** [comment]
Run this for Docker on Synology:

```
apk add --no-cache make gcc g++ python pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev
```

**Comment by sonoseco** [comment]
@tillkruss I used the suggested command to install the required packages and it was successful. I am running the Alpine version of the docker image. However, upon restarting homebridge I get the following errors:

`[4/28/2020, 5:35:11 PM] ====================
[4/28/2020, 5:35:11 PM] ERROR LOADING PLUGIN homebridge-unifi-protect-camera-motion:
[4/28/2020, 5:35:11 PM] Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node/lib/napi-v4/../../deps/lib/libtensorflow.so.1)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node/dist/index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[4/28/2020, 5:35:11 PM] ====================`

Any ideas? I already tried running the Debian version and installed required packages there but then could not install the plugin, had the same issue as here: https://github.com/oznu/docker-homebridge/issues/240

**Comment by sonoseco** [comment]
I was able to overcome the initial error, now this:

```
[4/28/2020, 8:52:03 PM] ====================
[4/28/2020, 8:52:03 PM] ERROR LOADING PLUGIN homebridge-unifi-protect-camera-motion:
[4/28/2020, 8:52:03 PM] Error: Error relocating /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node/lib/napi-v4/../../deps/lib/libtensorflow.so.1: __memcpy_chk: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node/dist/index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[4/28/2020, 8:52:03 PM] ====================
```

It looks like this plugin does not play well with the homebridge docker image and Synology. Compling tensorflow from source, which seems to be the problem, requires bazel and further compiling.

**Comment by tillkruss** [comment]
@sonoseco: Same error here:

```
Error: Error loading shared library ld-linux-x86-64.so.2
```

How did you fix it?

**Comment by tillkruss** [comment]
@sonoseco: If you find a solution to the `libtensorflow.so` error, can you let me know?

**Comment by sonoseco** [comment]
@tillkruss I could not compile libtensorflow in Alpine, so gave up on that. Tried again testing with the Debia version of the docker image and though the plugin seems to install fine with all dependencies, homebridge fails to load after a restart: `[HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGILL`. 

Unfortunately I don't think the plugin works with Synology docker-based images or more work is required. I have two Synology devices, same version of DSM/Docker, fresh install of homebride but different CPU architectures.  I was able to install the plugin on one device but it fails to load homebridge, the other device I was not even able to install the plugin and based my research, it could be related to tensorflow and the CPU instructions. I hope we can get input from @beele.

**Comment by tillkruss** [comment]
@sonoseco: Maybe we can build our own Docker container, or get https://github.com/oznu/docker-homebridge to fix support for it?

**Comment by tillkruss** [comment]
Also, 3.1.0 was released this morning, maybe that fixes it: https://github.com/oznu/docker-homebridge/releases

**Comment by sonoseco** [comment]
@tillkruss We are better off by creating an issue post in the docker-homebridge page.

**Comment by tillkruss** [comment]
@sonoseco: If you opened an issue, can you link it here?
