### ISSUE TITLE
Can't install on a Synology NAS

### ISSUE THREAD

**Issue by tronny87** [beele/homebridge-unifi-protect-camera-motion#31]
I understand your compile of tensorflow.js may not be compatible with certain CPU's and that a compile from source is needed, but I've had no luck with getting this to work in Docker on my Synology 918+.

As I saw on a previous thread that it is out of the scope of this project, I was hoping to get a hand with this. I had your plugin working on my RPi for months and recently migrated Homebridge over to my NAS and this is really killing me.

Any help is appreciated

**Comment by tronny87** [comment]
Further context:

====================
[5/5/2020, 4:21:24 PM] ERROR LOADING PLUGIN homebridge-unifi-protect-camera-motion:
[5/5/2020, 4:21:24 PM] Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node/lib/napi-v4/../../deps/lib/libtensorflow.so.1)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/@tensorflow/tfjs-node/dist/index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
[5/5/2020, 4:21:24 PM] ====================

**Comment by beele** [comment]
What output do you get during the installation of the plugin from npm?

**Comment by beele** [comment]
Your NAS has a CPU (Intel Celeron J3455) which lacks the AVX instruction and requires Tensorflow (and the bindings) to be compiled from scratch.
I suggest just running it on a rbpi

**Comment by beele** [comment]
For compiling the tensorflow lib yourself: https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source
