### ISSUE TITLE
After the latest update it can't work anymore

### ISSUE THREAD

**Issue by mrhsiao** [beele/homebridge-unifi-protect-camera-motion#43]
The requested platform "UnifiProtectMotion" was not registered by any plugin.
Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.

**Comment by alezanott** [comment]
Same for me. @beele Can you help us? 
```
25/5/2020, 15:54:55 HOOBS listening on port 8080.
25/5/2020, 15:55:06 Loaded plugin "homebridge-unifi-protect-camera-motion".
25/5/2020, 15:55:06 The requested platform "UnifiProtectMotion" was not registered by any plugin.
25/5/2020, 15:55:06 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.
25/5/2020, 15:55:06 Bridge is running on port 51826.
```

**Comment by beele** [comment]
Did you guys use:` sudo npm install homebridge-unifi-protect-camera-motion -g --unsafe-perm=true` to install the plugin?

Are you running V1.X.X of homebridge? Older versions are no longer supported.

**Comment by alezanott** [comment]
@beele I'm currently running everything on HOOBS. I've done the update as the previous ones, without any kind of issue. This time seems that there's an error in the update

**Comment by alezanott** [comment]
@beele 
I've just made a fresh install of HOOBS on my raspberry pi 3, now is impossible to install the updated plugin. Here the output:
```
> canvas@2.6.1 install /home/hoobs/.hoobs/node_modules/canvas
> node-pre-gyp install --fallback-to-build
25/6/2020, 23:12:12 node-pre-gyp
25/6/2020, 23:12:12  WARN Using request for node-pre-gyp https download
25/6/2020, 23:12:12 node-pre-gyp
25/6/2020, 23:12:12  WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
25/6/2020, 23:12:16 Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
25/6/2020, 23:12:16 gyp
25/6/2020, 23:12:16  ERR! configure error
25/6/2020, 23:12:16 gyp ERR! stack
25/6/2020, 23:12:16  Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
25/6/2020, 23:12:16 gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/hoobs/.hoobs/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/hoobs/.hoobs/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/hoobs/.hoobs/node_modules/canvas
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp
25/6/2020, 23:12:16  ERR! not ok
25/6/2020, 23:12:16 node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/hoobs/.hoobs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/hoobs/.hoobs/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hoobs/.hoobs/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
25/6/2020, 23:12:16 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.97-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/hoobs/.hoobs/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hoobs/.hoobs/node_modules/canvas
node-pre-gyp ERR! node -v v12.16.3
25/6/2020, 23:12:16 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
25/6/2020, 23:12:16 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/hoobs/.hoobs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/hoobs/.hoobs/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
25/6/2020, 23:12:17 npm
25/6/2020, 23:12:17  ERR! code ELIFECYCLE
npm ERR! errno 1
25/6/2020, 23:12:17 npm
25/6/2020, 23:12:17 ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
25/6/2020, 23:12:17 
25/6/2020, 23:12:17 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-06-25T21_12_17_454Z-debug.log
```

**Comment by alezanott** [comment]
@beele I've just made a fresh install of HOOBS and the plugin. I've encountered the same problem as before. Here the output:
```
25/6/2020, 23:20:45 Loaded plugin "homebridge-unifi-protect-camera-motion".
25/6/2020, 23:20:45 The requested platform "UnifiProtectMotion" was not registered by any plugin.
25/6/2020, 23:20:45 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.
25/6/2020, 23:20:45 Bridge is running on port 51826.
25/6/2020, 23:22:03 Got SIGINT, shutting down Bridge...
25/6/2020, 23:22:12 Loaded plugin "homebridge-unifi-protect-camera-motion".
25/6/2020, 23:22:12 The requested platform "UnifiProtectMotion" was not registered by any plugin.
25/6/2020, 23:22:12 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.
25/6/2020, 23:22:12 Bridge is running on port 51826.
```

**Comment by beele** [comment]
What does your config look like?
What node/homebridge/plugin versions are you using?

**Comment by alezanott** [comment]
> What does your config look like?
> What node/homebridge/plugin versions are you using?

@beele 
Here my config: ```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY82JP",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "IT",
        "postal_code": "20143"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "25:95:D8:D1:E5:78"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "UnifiProtectMotion",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect-camera-motion"
            },
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "controller": "https://192.168.1.254",
                "controller_rtsp": "https://192.168.1.254:7443",
                "username": "XXX",
                "password": "XXX",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": false,
                "enhanced_motion_score": 50,
                "enhanced_classes": [
                    "person"
                ],
                "save_snapshot": false,
                "debug": false
            },
            "googlePhotos": {
                "upload_gphotos": false,
                "auth_redirectUrl": "http://localhost:8080/oauth2-callback",
                "auth_clientId": "",
                "auth_clientSecret": ""
            },
            "videoConfig": {
                "maxStreams": 2,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 15,
                "maxBitrate": 3000,
                "vcodec": "libx264",
                "packetSize": 376,
                "audio": false,
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
            },
            "videoProcessor": ""
        }
    ]
}
```

Node at version v12.16.3, plugin at 0.3.4, I can only find the HOOBS version that is 3.2.6

**Comment by beele** [comment]
Can you provide a full log when you start up homebridge, cause this is most likely caused by an error when loading the plugin

**Comment by alezanott** [comment]
> Can you provide a full log when you start up homebridge, cause this is most likely caused by an error when loading the plugin

@beele do i need just to activate the verbose mode? can you give me in case the right command to have the full log of the startup sequence of homebridge? thank you

**Comment by beele** [comment]
Add the debug: true field to the config and then just pipe the homebridge output to a .txt file (redact where needed) and add it here

**Comment by alezanott** [comment]
[Log.txt](https://github.com/beele/homebridge-unifi-protect-camera-motion/files/4971052/Log.txt)
@beele Here the log.

**Comment by beele** [comment]
0.4.1 has been released.
I've got it running on my rbpi 4 with lastest homebridge and config-ui

**Comment by beele** [comment]
```
{
            "platform": "UnifiProtectMotion",
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "controller": "https://192.168.1.10:7443",
                "controller_rtsp": "rtsp://192.168.1.10:7447",
                "username": "USERNAME",
                "password": "PASSWORD",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 0,
                "enhanced_motion": true,
                "enhanced_motion_score": 55,
                "enhanced_classes": [
                    "person"
                ],
                "save_snapshot": false,
                "enable_motion_trigger": true,
                "enable_doorbell_for": [],
                "debug": false,
                "debug_network_traffic": false
            },
            "googlePhotos": {
                "upload_gphotos": false,
                "auth_clientId": "CLIENT_ID",
                "auth_clientSecret": "CLIENT_SECRET",
                "auth_redirectUrl": "http://localhost:8080/oauth2-callback"
            },
            "videoConfig": {
                "vcodec": "h264_omx",
                "audio": true,
                "maxStreams": 2,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 15,
                "mapvideo": "0:1",
                "mapaudio": "0:0",
                "maxBitrate": "3000",
                "packetSize": 188,
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
            }
        }
```

where you can replace h264_omx with h264 when not running on a rbpi

**Comment by beele** [comment]
continued in #66
