### ISSUE TITLE
Unable to load plugin after update

### ISSUE THREAD

**Issue by alezanott** [beele/homebridge-unifi-protect-camera-motion#66]
I'm running the plugin on HOOBS. I've also run the command `npm rebuild @tensorflow/tfjs-node build-addon-from-source` to rebuild Tensorflow, but nothing changed. 
Any clue of what's going on @beele ?
Here the output:
```
4/8/2020, 11:00:05 Error loading plugin "homebridge-unifi-protect-camera-motion".
4/8/2020, 11:00:05 Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node. 
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module. 
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-unifi-protect-camera-motion/src/motion/coco/coco.js:23:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
4/8/2020, 11:00:05 No plugins found.
4/8/2020, 11:00:05 The requested platform "UnifiProtectMotion" was not registered by any plugin.
4/8/2020, 11:00:05 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.
4/8/2020, 11:00:05 Bridge is running on port 51826.
```

**Comment by beele** [comment]
Check: https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md and reinstall the plugin

**Comment by alezanott** [comment]
> Check: https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md and reinstall the plugin

Thank you @beele. Reinstalling the plugin will also fix the registration problem?

**Comment by beele** [comment]
@alezanott the registration problem is because the plugin crashed due to the missing node bindings. Once that is resolved the platform registration should work fine during startup.

**Comment by alezanott** [comment]
@beele I've followed the guide on that link but basically it didn't brought to nothing. Is possible that on HOOBS not is not running with root privileges, so I get this kind of error?

**Comment by beele** [comment]
@alezanott can you try with the latest beta, login on hoobs, open a terminal and execute: 
`sudo npm i homebridge-unifi-protect-camera-motion@0.4.2-beta.9 --unsafe-perm=true`
I've formatted a backup pi with hoobs and after some trial and error got it running (hopefully I did not break it for non hoobs installs :/)

**Comment by alezanott** [comment]
Thank you @beele. Now everything is working fine! When you will release the final version of 0.4.2 will HOOBS automatically update to the correct version or do I need to uninstall the beta and then reinstall the final one?

**Comment by beele** [comment]
@alezanott It should be fine, I've release 0.4.2, can you try updating to it and see if it still works?

**Comment by beele** [comment]
Closing due to inactivity
